openapi_url: /v1/model-workbench/openapi.json
docs_url: /v1/workbench/docs
title: Infosys Responsible AI - Model & DataSet - OpenAPI 3.0
summary: API specs for Infosys Responsible AI Model-Details pillar in OpenAPI 3.0 format
terms_of_service: https://www.infosys.com
contact:
    email: Impact@infosys.com
license_info:
    name: Infosys
    url: https://www.infosys.com
description: "Copyright \u00A9 2023 Infosys Limited | Internal Communications - HRD"
version: v$version
openapi_tags:
    - name: Model & DataSet Details
      description: ""
      externalDocs:
        description: Find out more
        url: https://www.infosys.com
